"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.products  void 0;
exports.products  [
    {
        id: "env-check",
        name: "env-check",
        description: "Environment variable validator with merge, conflict detection, and secret scanning",
        category: "cli-tools",
        npmInstall: "npm install env-check",
        version: "0.2.0",
    },
    {
        id: "pool-leak-detector",
        name: "Pool Leak Detector",
        description: "Database connection leak detection for Node.js applications",
        category: "database",
        npmInstall: "npm install pool-leak-detector",
        version: "0.1.0",
    },
    {
        id: "explain-analyzer",
        name: "Explain Analyzer",
        description: "PostgreSQL EXPLAIN output analyzer for query optimization",
        category: "database",
        npmInstall: "npm install explain-analyzer",
        version: "0.1.0",
    },
    {
        id: "query-pattern-analyzer",
        name: "Query Pattern Analyzer",
        description: "SQL pattern analysis and anomaly detection",
        category: "database",
        npmInstall: "npm install query-pattern-analyzer",
        version: "0.1.0",
    },
    {
        id: "migration-validator",
        name: "Migration Validator",
        description: "Database migration validation and rollback safety checks",
        category: "database",
        npmInstall: "npm install migration-validator",
        version: "0.1.0",
    },
    {
        id: "k8s-config-auditor",
        name: "K8s Config Auditor",
        description: "Kubernetes configuration linting and best practices",
        category: "devops",
        npmInstall: "npm install k8s-config-auditor",
        version: "0.1.0",
    },
    {
        id: "dockerfile-linter",
        name: "Dockerfile Linter",
        description: "Dockerfile best practices and security linting",
        category: "devops",
        npmInstall: "npm install dockerfile-linter",
        version: "0.1.0",
    },
    {
        id: "serverless-security-scanner",
        name: "Serverless Security Scanner",
        description: "Security scanner for serverless functions and Lambda",
        category: "security",
        npmInstall: "npm install serverless-security-scanner",
        version: "0.1.0",
    },
    {
        id: "api-security-scanner",
        name: "API Security Scanner",
        description: "API endpoint security vulnerability scanner",
        category: "security",
        npmInstall: "npm install api-security-scanner",
        version: "0.1.0",
    },
    {
        id: "dep-breakage-detector",
        name: "Dependency Breakage Detector",
        description: "Detect breaking changes in dependency updates",
        category: "cli-tools",
        npmInstall: "npm install dep-breakage-detector",
        version: "0.1.0",
    },
    {
        id: "secret-rotation-detector",
        name: "Secret Rotation Detector",
        description: "Alert on secrets that need rotation",
        category: "security",
        npmInstall: "npm install secret-rotation-detector",
        version: "0.1.0",
    },
    {
        id: "npm-vuln-autofixer",
        name: "NPM Vulnerability Auto-Fixer",
        description: "Automatically fix npm security vulnerabilities",
        category: "security",
        npmInstall: "npm install npm-vuln-autofixer",
        version: "0.1.0",
    },
    {
        id: "npm-run-info",
        name: "NPM Run Info",
        description: "Inspector for npm scripts and run commands",
        category: "cli-tools",
        npmInstall: "npm install npm-run-info",
        version: "0.1.0",
    },
    {
        id: "port-available",
        name: "Port Available",
        description: "Check if a port is available for binding",
        category: "cli-tools",
        npmInstall: "npm install port-available",
        version: "0.1.0",
    },
    {
        id: "command-vault",
        name: "Command Vault",
        description: "Manage and organize command snippets",
        category: "cli-tools",
        npmInstall: "npm install command-vault",
        version: "0.1.0",
    },
    {
        id: "scriptforge",
        name: "Scriptforge",
        description: "Script management and execution framework",
        category: "cli-tools",
        npmInstall: "npm install scriptforge",
        version: "0.1.0",
    },
    {
        id: "metasync",
        name: "Metasync",
        description: "Meta information synchronization tool",
        category: "cli-tools",
        npmInstall: "npm install metasync",
        version: "0.1.0",
    },
    {
        id: "depsearch",
        name: "Dependency Search",
        description: "Search and explore package dependencies",
        category: "cli-tools",
        npmInstall: "npm install depsearch",
        version: "0.1.0",
    },
    {
        id: "env-safe",
        name: "Env Safe",
        description: "Environment variable safety validator",
        category: "security",
        npmInstall: "npm install env-safe",
        version: "0.1.0",
    },
    {
        id: "secret-leak-scanner",
        name: "Secret Leak Scanner",
        description: "Scan code for leaked secrets and credentials",
        category: "security",
        npmInstall: "npm install secret-leak-scanner",
        version: "0.1.0",
    },
    {
        id: "unused-deps-scanner",
        name: "Unused Dependencies Scanner",
        description: "Find and remove unused package dependencies",
        category: "cli-tools",
        npmInstall: "npm install unused-deps-scanner",
        version: "0.1.0",
    },
    {
        id: "test-coverage-diff",
        name: "Test Coverage Diff",
        description: "Check test coverage between commits",
        category: "testing",
        npmInstall: "npm install test-coverage-diff",
        version: "0.1.0",
    },
    {
        id: "env-diff",
        name: "Environment Diff",
        description: "Compare environment configurations across stages",
        category: "devops",
        npmInstall: "npm install env-diff",
        version: "0.1.0",
    },
    {
        id: "branch-cleanup-cli",
        name: "Branch Cleanup CLI",
        description: "Clean up merged and stale Git branches",
        category: "cli-tools",
        npmInstall: "npm install branch-cleanup-cli",
        version: "0.1.0",
    },
    {
        id: "pr-title-generator",
        name: "PR Title Generator",
        description: "Generate conventional commit PR titles",
        category: "devops",
        npmInstall: "npm install pr-title-generator",
        version: "0.1.0",
    },
    {
        id: "dependency-graph-cli",
        name: "Dependency Graph CLI",
        description: "Visualize project dependency graph",
        category: "cli-tools",
        npmInstall: "npm install dependency-graph-cli",
        version: "0.1.0",
    },
    {
        id: "lockfile-analyzer",
        name: "Lockfile Analyzer",
        description: "Analyze package lockfiles for security and updates",
        category: "cli-tools",
        npmInstall: "npm install lockfile-analyzer",
        version: "0.1.0",
    },
    {
        id: "release-cli",
        name: "Release CLI",
        description: "Automated release and version management",
        category: "devops",
        npmInstall: "npm install release-cli",
        version: "0.1.0",
    },
    {
        id: "ci-config-validator",
        name: "CI Config Validator",
        description: "Validate CI/CD configuration files",
        category: "devops",
        npmInstall: "npm install ci-config-validator",
        version: "0.1.0",
    },
    {
        id: "bundle-size-analyzer",
        name: "Bundle Size Analyzer",
        description: "Analyze JavaScript bundle sizes",
        category: "performance",
        npmInstall: "npm install bundle-size-analyzer",
        version: "0.1.0",
    },
    {
        id: "perf-budget-cli",
        name: "Performance Budget CLI",
        description: "Enforce performance budgets in builds",
        category: "performance",
        npmInstall: "npm install perf-budget-cli",
        version: "0.1.0",
    },
    {
        id: "lighthouse-ci-wrapper",
        name: "Lighthouse CI Wrapper",
        description: "Simplified Lighthouse CI integration",
        category: "performance",
        npmInstall: "npm install lighthouse-ci-wrapper",
        version: "0.1.0",
    },
];
