param(
    [string]$Distro ***REMOVED*** "Ubuntu",
    [string]$Model,
    [int]$LoopInterval,
    [int]$CycleTimeoutSeconds,
    [int]$MaxConsecutiveErrors,
    [int]$CooldownSeconds,
    [int]$LimitWaitSeconds,
    [int]$MaxLogs,
    [string]$CodexSandboxMode
)

$ErrorActionPreference ***REMOVED*** "Stop"

function Assert-WslAvailable {
    if (-not (Get-Command wsl.exe -ErrorAction SilentlyContinue)) {
        throw "wsl.exe not found. Enable WSL first."
    }
}

function Get-RepoPaths {
    $repoWin ***REMOVED*** (Resolve-Path (Join-Path $PSScriptRoot "..\\..")).Path
    $repoWinForWsl ***REMOVED*** $repoWin -replace "\\", "/"
    $repoWslRaw ***REMOVED*** & wsl.exe wslpath -a "$repoWinForWsl"
    if (-not $repoWslRaw) {
        throw "Failed to convert repository path to WSL path."
    }
    $repoWsl ***REMOVED*** $repoWslRaw.Trim()
    if (-not $repoWsl) {
        throw "Failed to convert repository path to WSL path."
    }
    return @{
        RepoWin ***REMOVED*** $repoWin
        RepoWsl ***REMOVED*** $repoWsl
    }
}

function Invoke-WslCommand {
    param(
        [Parameter(Mandatory ***REMOVED*** $true)][string]$RepoWsl,
        [Parameter(Mandatory ***REMOVED*** $true)][string]$Command,
        [switch]$IgnoreExitCode
    )

    $output ***REMOVED*** & wsl.exe -d $Distro --cd $RepoWsl bash -lc $Command 2>&1
    $code ***REMOVED*** $LASTEXITCODE
    if ($output) {
        foreach ($line in $output) {
            Write-Host $line
        }
    }
    if (-not $IgnoreExitCode -and $code -ne 0) {
        throw "WSL command failed ($code): $Command"
    }
    return $code
}

function Write-AutoLoopEnv {
    param(
        [Parameter(Mandatory ***REMOVED*** $true)][string]$RepoWin,
        [string[]]$EnvLines ***REMOVED*** @()
    )

    $envFile ***REMOVED*** Join-Path $RepoWin ".auto-loop.env"
    $lines ***REMOVED*** @(
        "# Auto-generated by start-win.ps1 at $(Get-Date -Format o)",
        "# Edit manually only if you know what you are doing."
    )
    $lines +***REMOVED*** $EnvLines

    $utf8NoBom ***REMOVED*** New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($envFile, $lines, $utf8NoBom)
    Write-Host "Wrote env file: $envFile"
}

Assert-WslAvailable
$paths ***REMOVED*** Get-RepoPaths
$repoWin ***REMOVED*** $paths.RepoWin
$repoWsl ***REMOVED*** $paths.RepoWsl

if ($PSBoundParameters.ContainsKey("CycleTimeoutSeconds") -and $CycleTimeoutSeconds -lt 300) {
    Write-Warning "CycleTimeoutSeconds***REMOVED***$CycleTimeoutSeconds is very low for real cycles and may cause frequent timeouts. Recommended: 900-1800."
}

$envLines ***REMOVED*** @()
if ($PSBoundParameters.ContainsKey("Model")) { $envLines +***REMOVED*** "MODEL***REMOVED***$Model" }
if ($PSBoundParameters.ContainsKey("LoopInterval")) { $envLines +***REMOVED*** "LOOP_INTERVAL***REMOVED***$LoopInterval" }
if ($PSBoundParameters.ContainsKey("CycleTimeoutSeconds")) { $envLines +***REMOVED*** "CYCLE_TIMEOUT_SECONDS***REMOVED***$CycleTimeoutSeconds" }
if ($PSBoundParameters.ContainsKey("MaxConsecutiveErrors")) { $envLines +***REMOVED*** "MAX_CONSECUTIVE_ERRORS***REMOVED***$MaxConsecutiveErrors" }
if ($PSBoundParameters.ContainsKey("CooldownSeconds")) { $envLines +***REMOVED*** "COOLDOWN_SECONDS***REMOVED***$CooldownSeconds" }
if ($PSBoundParameters.ContainsKey("LimitWaitSeconds")) { $envLines +***REMOVED*** "LIMIT_WAIT_SECONDS***REMOVED***$LimitWaitSeconds" }
if ($PSBoundParameters.ContainsKey("MaxLogs")) { $envLines +***REMOVED*** "MAX_LOGS***REMOVED***$MaxLogs" }
if ($PSBoundParameters.ContainsKey("CodexSandboxMode")) { $envLines +***REMOVED*** "CODEX_SANDBOX_MODE***REMOVED***$CodexSandboxMode" }

Write-AutoLoopEnv -RepoWin $repoWin -EnvLines $envLines

$null ***REMOVED*** Invoke-WslCommand -RepoWsl $repoWsl -Command "command -v systemctl >/dev/null 2>&1 && systemctl --user --version >/dev/null 2>&1"

$installedCode ***REMOVED*** Invoke-WslCommand -RepoWsl $repoWsl -Command "systemctl --user cat auto-company.service >/dev/null 2>&1" -IgnoreExitCode
if ($installedCode -ne 0) {
    Write-Host "auto-company.service not installed; running make install..."
    $null ***REMOVED*** Invoke-WslCommand -RepoWsl $repoWsl -Command "make install"
}

$null ***REMOVED*** Invoke-WslCommand -RepoWsl $repoWsl -Command "systemctl --user start auto-company.service"
Write-Host "WSL daemon started: auto-company.service"

$awakeScript ***REMOVED*** Join-Path $repoWin "scripts\\windows\\awake-guardian-win.ps1"
if (-not (Test-Path $awakeScript)) {
    throw "Missing awake guardian script: $awakeScript"
}

& $awakeScript -Action start
if ($LASTEXITCODE -ne 0) {
    Write-Error "Daemon started, but awake guardian failed to start. System sleep is not protected."
    exit 2
}

$anchorScript ***REMOVED*** Join-Path $repoWin "scripts\\windows\\wsl-anchor-win.ps1"
if (-not (Test-Path $anchorScript)) {
    throw "Missing WSL anchor script: $anchorScript"
}

& $anchorScript -Action start -Distro $Distro -RepoWsl $repoWsl
if ($LASTEXITCODE -ne 0) {
    Write-Error "Daemon started, but WSL anchor failed to start. Background persistence may be unstable."
    exit 3
}

Write-Host ""
Write-Host "Use .\scripts\windows\status-win.ps1 to inspect daemon and loop status."
exit 0
